# Generated by Django 4.0.6 on 2022-07-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dateComplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
